using ClassWestWindSystem.DAL;
using ClassWestWindSystem.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassWestWindSystem.BLL
{
    public class ProductServices
    {
        #region setup of the connect connection variable and the class constructor
        //this class will create an instance of the WestWindContext class
        //  everytime that a service is used by the outside user

        //any method (aka service) will probably need access to our database
        //this will be done via the context class (WestWindContext)
        //during the instantiation of this service class, we will create
        //  an instance of the context class
        //we will save this instance in a private variable usable throughout the class
        //during the instantiation of this service class the constructor will
        //  receive as a parameter of the registered connection from the IServiceCollection

        private readonly WestWindContext _context;

        internal ProductServices(WestWindContext registeredcontext)
        {
            _context = registeredcontext;

        }

        #endregion

        // basic queries to fetch existing product details

        public List<Product> Product_GetByCategoryID(int categoryid)
        {
            
            List<Product> info = _context.Products.Where(x => x.CategoryId == categoryid)
                .OrderBy(x => x.ProductName)
                .ToList();

            return info;
        }

        // method tp fetch product by product id

        public Product Product_GetByProductID(int productid)
        {

            Product info = _context.Products.Where(x => x.ProductId == productid)
                            .FirstOrDefault();
                

            return info;
        }


        // your CRUD operations

        // create new product service by using entries in the editform

        public int Product_Add(Product item)
        {

            //Adding a record to your database may require addition validation that was not
            //  done on the front end
            //Such validation could be
            //  was data actually passed to the method
            //  the pkey may not be created on the database, it is user supplied
            //      the pkey key supplied should be tested to see if it already exists on the database
            //  there could be a set of business rules that evolve checking data against
            //      existing data on the database that is not part of the record being added

            //do any validation needed within the service method

            //  was data actually passed to the method
            if (item == null)
            {
                throw new ArgumentNullException("Product information was not received. Add not done.");
            }

            //does the pkey exist?
            //product has a pkey of IDENTITY
            //there is no need to check to see if the pkey already exists since the
            //      primary key will be generated by the database
            //HOWEVER, if your pkey is NOT an identity, you could check to see if
            //  the value for the pkey is already in use, if so, throw an exception



            //are there any other business rules to check
            //YOU MAY NOT HAVE ANY OTHER BUSINESS RULES TO CHECK!!!!!!!!!!!!!!!!!!!
            //An example of business rules (product duplication) for this demo could be that the product
            //  a) is from the same supplier
            //  b) with the same product name
            //  c) having the same quantity per unit

            bool exists = false; //flag

            //the method does NOT need the actual record, JUST needs to know if the condition exists: .Any(...)
            exists = _context.Products
                            .Any(x => x.SupplierId == item.SupplierId
                                   && x.ProductName.Equals(item.ProductName)
                                   && x.QuantityPerUnit.Equals(item.QuantityPerUnit));

            //check the results of your complex business rule
            if (exists)
                throw new ArgumentException($"Product {item.ProductName} from " +
                    $" {item.Supplier.CompanyName} of size {item.QuantityPerUnit} " +
                    $" already on file.");


            //after all business rules have been passed, you can assume the 
            //  data is good to be placed on the database

            //if your field is an IDENTITY key then override any value in the field 
            //set the pkey value to zero
            //prevents an IDENTITY_INSERT flag problem from occuring
            item.ProductId = 0;

            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging
            //EntityFramework sets up all db processing in local memory first
            //what is needed for staging
            // a) know the DbSet : Products
            // b) know the action : Add
            // c) know the instance of the DbSet to use: item

            //IMPORTANT: the data is in LOCAL MEMORY
            //           the data is NOT!!! yet been sent to the database
            //THEREFORE: at this time, there is NO!!!!! IDENTITY primary key value
            //              on this instance (except for the default of the datatype)
            //UNLESS: you have place a value in the NON_IDENTITY key field(s)

            _context.Products.Add(item);

            //Commit
            // this sends ALL staged data in local memory to the database for processing

            //ANY annotation validation is in your entity, it is executed to validate the data
            //  going to the database
            //if there is a validation problem then an exception is thrown and processing of
            //  the commit is terminated (transaction RollBack)

            _context.SaveChanges();

            //AFTER the successful commit to the database, your new product id
            //  primary key is available to you via the item.ProductID
            //Optionally, you could return this value to the calling process

            return item.ProductId;
        }




    }
}
